python Test.py user1 point_1
python Test.py user1 point_2
python Test.py user1 point_3
python Test.py user1 point_4
python Test.py user1 point_5
python Test.py user1 point_6
python Test.py user1 point_7
python Test.py user1 point_8
python Test.py user1 point_9
python Test.py user1 point_10
python Test.py user1 show_1
python Test.py user1 show_2
python Test.py user1 show_3
python Test.py user1 show_4
python Test.py user1 show_5
python Test.py user1 show_6
python Test.py user1 show_7
python Test.py user1 show_8
python Test.py user1 show_9
python Test.py user1 show_10
python Test.py user2 point_1
python Test.py user2 point_2
python Test.py user2 point_3
python Test.py user2 point_4
python Test.py user2 point_5
python Test.py user2 point_6
python Test.py user2 point_7
python Test.py user2 point_8
python Test.py user2 point_9
python Test.py user2 point_10
python Test.py user2 show_1
python Test.py user2 show_2
python Test.py user2 show_3
python Test.py user2 show_4
python Test.py user2 show_5
python Test.py user2 show_6
python Test.py user2 show_7
python Test.py user2 show_8
python Test.py user2 show_9
python Test.py user2 show_10
python Test.py user3 point_1
python Test.py user3 point_2
python Test.py user3 point_3
python Test.py user3 point_4
python Test.py user3 point_5
python Test.py user3 point_6
python Test.py user3 point_7
python Test.py user3 point_8
python Test.py user3 point_9
python Test.py user3 point_10
python Test.py user3 show_1
python Test.py user3 show_2
python Test.py user3 show_3
python Test.py user3 show_4
python Test.py user3 show_5
python Test.py user3 show_6
python Test.py user3 show_7
python Test.py user3 show_8
python Test.py user3 show_9
python Test.py user3 show_10
python Test.py user4 point_1
python Test.py user4 point_2
python Test.py user4 point_3
python Test.py user4 point_4
python Test.py user4 point_5
python Test.py user4 point_6
python Test.py user4 point_7
python Test.py user4 point_8
python Test.py user4 point_9
python Test.py user4 point_10
python Test.py user4 show_1
python Test.py user4 show_2
python Test.py user4 show_3
python Test.py user4 show_4
python Test.py user4 show_5
python Test.py user4 show_6
python Test.py user4 show_7
python Test.py user4 show_8
python Test.py user4 show_9
python Test.py user4 show_10
python Test.py user5 point_1
python Test.py user5 point_2
python Test.py user5 point_3
python Test.py user5 point_4
python Test.py user5 point_5
python Test.py user5 point_6
python Test.py user5 point_7
python Test.py user5 point_8
python Test.py user5 point_9
python Test.py user5 point_10
python Test.py user5 show_1
python Test.py user5 show_2
python Test.py user5 show_3
python Test.py user5 show_4
python Test.py user5 show_5
python Test.py user5 show_6
python Test.py user5 show_7
python Test.py user5 show_8
python Test.py user5 show_9
python Test.py user5 show_10
python Test.py user6 point_1
python Test.py user6 point_2
python Test.py user6 point_3
python Test.py user6 point_4
python Test.py user6 point_5
python Test.py user6 point_6
python Test.py user6 point_7
python Test.py user6 point_8
python Test.py user6 point_9
python Test.py user6 point_10
python Test.py user6 show_1
python Test.py user6 show_2
python Test.py user6 show_3
python Test.py user6 show_4
python Test.py user6 show_5
python Test.py user6 show_6
python Test.py user6 show_7
python Test.py user6 show_8
python Test.py user6 show_9
python Test.py user6 show_10
python Test.py user7 point_1
python Test.py user7 point_2
python Test.py user7 point_3
python Test.py user7 point_4
python Test.py user7 point_5
python Test.py user7 point_6
python Test.py user7 point_7
python Test.py user7 point_8
python Test.py user7 point_9
python Test.py user7 point_10
python Test.py user7 show_1
python Test.py user7 show_2
python Test.py user7 show_3
python Test.py user7 show_4
python Test.py user7 show_5
python Test.py user7 show_6
python Test.py user7 show_7
python Test.py user7 show_8
python Test.py user7 show_9
python Test.py user7 show_10
python Test.py user8 point_1
python Test.py user8 point_2
python Test.py user8 point_3
python Test.py user8 point_4
python Test.py user8 point_5
python Test.py user8 point_6
python Test.py user8 point_7
python Test.py user8 point_8
python Test.py user8 point_9
python Test.py user8 point_10
python Test.py user8 show_1
python Test.py user8 show_2
python Test.py user8 show_3
python Test.py user8 show_4
python Test.py user8 show_5
python Test.py user8 show_6
python Test.py user8 show_7
python Test.py user8 show_8
python Test.py user8 show_9
python Test.py user8 show_10
python Test.py user9 point_1
python Test.py user9 point_2
python Test.py user9 point_3
python Test.py user9 point_4
python Test.py user9 point_5
python Test.py user9 point_6
python Test.py user9 point_7
python Test.py user9 point_8
python Test.py user9 point_9
python Test.py user9 point_10
python Test.py user9 show_1
python Test.py user9 show_2
python Test.py user9 show_3
python Test.py user9 show_4
python Test.py user9 show_5
python Test.py user9 show_6
python Test.py user9 show_7
python Test.py user9 show_8
python Test.py user9 show_9
python Test.py user9 show_10
python Test.py user10 point_1
python Test.py user10 point_2
python Test.py user10 point_3
python Test.py user10 point_4
python Test.py user10 point_5
python Test.py user10 point_6
python Test.py user10 point_7
python Test.py user10 point_8
python Test.py user10 point_9
python Test.py user10 point_10
python Test.py user10 show_1
python Test.py user10 show_2
python Test.py user10 show_3
python Test.py user10 show_4
python Test.py user10 show_5
python Test.py user10 show_6
python Test.py user10 show_7
python Test.py user10 show_8
python Test.py user10 show_9
python Test.py user10 show_10