#python Experiments_manual.py SIFT 10
#python Experiments_manual.py ORB 10
python Experiments_manual.py HC 10
#python Experiments_manual.py FC7 10
#python Experiments_manual.py SIFT 20
#python Experiments_manual.py ORB 20
python Experiments_manual.py HC 20
#python Experiments_manual.py FC7 20
#python Experiments_manual.py SIFT 30
#python Experiments_manual.py ORB 30
python Experiments_manual.py HC 30
#python Experiments_manual.py FC7 30
#python Experiments_manual.py SIFT 20000
#python Experiments_manual.py ORB 20000
python Experiments_manual.py HC 20000
#python Experiments_manual.py FC7 20000
