python Test.py user1 talk_1
python Test.py user1 talk_2
python Test.py user2 talk_1
python Test.py user2 talk_2
python Test.py user3 talk_1
python Test.py user3 talk_2
python Test.py user4 talk_1
python Test.py user4 talk_2
python Test.py user5 talk_1
python Test.py user5 talk_2
python Test.py user6 talk_1
python Test.py user6 talk_2
python Test.py user7 talk_1
python Test.py user7 talk_2
python Test.py user8 talk_1
python Test.py user8 talk_2
python Test.py user9 talk_1
python Test.py user9 talk_2
python Test.py user10 talk_1
python Test.py user10 talk_2
